add_newline = false

format = """
$time$battery\
$git_branch$git_commit$git_state$git_status\
$kubernetes$docker_context$cmake$java$python$nodejs
$username$hostname$directory$jobs$status$cmd_duration$shlvl$character
"""

[cmd_duration]
format = "[$duration]($style) "
style = "dimmed white"
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)

[package]
disabled = true

[username]
style_user = "cyan"
style_root = "bold purple"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "@(white)[$hostname](yellow) "
disabled = false

[directory]
truncation_length = 2
truncation_symbol = "../"
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bright-white"

[character]
success_symbol = "[|>](bright-white)"
error_symbol = "[*>](bold red)"

[time]
disabled = false
format = "[\\[$time\\]]($style) "
style = "dimmed white"

[battery]
format = "[\\[$symbol $percentage\\]]($style) "
disabled = false

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "yellow"

[[battery.display]]
threshold = 100
style = "green"

[status]
format = '[\[$symbol$status\]]($style) '
disabled = false

[shlvl]
threshold = 3
disabled = false
format = "[$symbol$shlvl]($style) "
symbol = "\\$ "

[git_branch]
format = "[\\[$symbol $branch\\]]($style) "
symbol = ""

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = ""
modified = "[](yellow)"

# ----------------------Languages----------------------
[java]
format = "[\\[${symbol} ${version}\\]]($style) "
symbol = ""
style = "red"

[python]
format = "[\\[${symbol} ${pyenv_prefix}${version}(\\($virtualenv\\))\\]]($style) "
style = "green"
symbol = ""

[nodejs]
format = "[\\[[$symbol $version]($style)\\]]($style) "
style = "blue"
symbol = ""
